### ISSUE TITLE
Alignement des champs "Ajout Élèves"

### ISSUE THREAD

**Issue by droumanet** [thibautscheers/FOLOZEM#12]
Voir support de cours "labels" sur 
[cours formulaires.html](http://david.roumanet.free.fr/BTS-SIO/Bloc1-Dev/102%20HTML/B1-Dev%20-%2002-2%20cours%20formulaires%20HTML.pdf)

**Comment by droumanet** [comment]
Sur ce point, il y a deux améliorations à faire : 

- [ ] décaler l'ensemble (ne pas laisser le texte collé contre le bord gauche du navigateur)
- [ ] élargir les labels de 150 pixels environ
![image](https://user-images.githubusercontent.com/24438463/177825523-384028e3-2b15-4682-9495-c1a2694e8e68.png)

**Comment by thibautscheers** [comment]
Nouvelle version en ligne 
![image](https://user-images.githubusercontent.com/95413301/177932647-a0e777ce-a9c2-48df-bc9c-337ecc4a31bb.png)
