### ISSUE TITLE
Modifier l'aspect de la liste des étudiants

### ISSUE THREAD

**Issue by droumanet** [thibautscheers/FOLOZEM#14]
Les champs de modification à droite allongent trop la hauteur de chaque ligne.
Il faut réduire cette hauteur : la proposition est de placer chaque champ sous sa description.
![image](https://user-images.githubusercontent.com/24438463/177789647-2988e50c-97d0-4354-a89e-3a70153f79ef.png)

**Comment by thibautscheers** [comment]
![image](https://user-images.githubusercontent.com/95413301/177804799-9e10d64c-e36a-4c0a-aeb6-153beb2abc8e.png)
